M48
; DRILL file {KiCad 9.0.2} date 2025-05-23T00:22:45+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-23T00:22:45+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X164.075Y-35.53
X168.925Y-35.53
T2
X163.775Y-32.5
X169.225Y-32.5
T3
X57.548Y-56.608
X57.548Y-78.452
X93.87Y-56.608
X93.87Y-78.452
M30
