M48
; DRILL file {KiCad 9.0.2} date 2025-05-22T21:13:22+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-05-22T21:13:22+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.000
%
G90
G05
T1
X205.075Y-51.53
X209.925Y-51.53
T2
X204.775Y-48.5
X210.225Y-48.5
T3
X107.548Y-49.548
X107.548Y-85.87
X129.392Y-49.548
X129.392Y-85.87
M30
